title: The Moose Den
author: @Moose0621
email: moose0621@github.com
description: > # this means to ignore newlines until "baseurl:"
My website blog will focus on random thoughts and other things. 
# social links
twitter_username: @mcmoose3
github_username:  @moose0621
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
